### ISSUE TITLE
We need more pictures.

### ISSUE THREAD

**Issue by LaiShengjie** [wcjochem/test#1]

**Comment by LaiShengjie** [comment]
We need more pictures.
![img_0449](https://user-images.githubusercontent.com/16002281/48194736-c4467300-e345-11e8-9cbf-daea0bf66205.JPG)

**Comment by wcjochem** [comment]
Should they be cats?

**Comment by wcjochem** [comment]
Photo added #7c87501

**Comment by LaiShengjie** [comment]
It is a moon. I took the photo in Lancaster last year.
